// Code generated by "stringer -type=LoginCode --linecomment"; DO NOT EDIT.

package e

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NOT_CONFIRM - -5]
	_ = x[NOT_SCAN - -4]
	_ = x[KEY_TIMEOUT - -2]
	_ = x[KEY_INVALID - -1]
}

const (
	_LoginCode_name_0 = "已扫码，未确认等待扫码"
	_LoginCode_name_1 = "秘钥超时秘钥无效"
)

var (
	_LoginCode_index_0 = [...]uint8{0, 21, 33}
	_LoginCode_index_1 = [...]uint8{0, 12, 24}
)

func (i LoginCode) String() string {
	switch {
	case -5 <= i && i <= -4:
		i -= -5
		return _LoginCode_name_0[_LoginCode_index_0[i]:_LoginCode_index_0[i+1]]
	case -2 <= i && i <= -1:
		i -= -2
		return _LoginCode_name_1[_LoginCode_index_1[i]:_LoginCode_index_1[i+1]]
	default:
		return "LoginCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
