// Code generated by "stringer -type=ResponseCode --linecomment"; DO NOT EDIT.

package e

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RespCode_Success-0]
	_ = x[RespCode_ParamError-1]
	_ = x[RespCode_LoginTimeout-2]
	_ = x[RespCode_LoginError-3]
	_ = x[RespCode_GetDynamicError-4]
	_ = x[RespCode_ReplyError-5]
	_ = x[RespCode_RefreshError-6]
}

const _ResponseCode_name = "成功参数错误登录超时登录错误获取动态错误回复错误刷新错误"

var _ResponseCode_index = [...]uint8{0, 6, 18, 30, 42, 60, 72, 84}

func (i ResponseCode) String() string {
	if i < 0 || i >= ResponseCode(len(_ResponseCode_index)-1) {
		return "ResponseCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseCode_name[_ResponseCode_index[i]:_ResponseCode_index[i+1]]
}
