// Code generated by "stringer -type=Status --linecomment"; DO NOT EDIT.

package basetask

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Running-0]
	_ = x[Warning-1]
}

const _Status_name = "运行中发生错误"

var _Status_index = [...]uint8{0, 9, 21}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
