// Code generated by "stringer -type=TaskStatus --linecomment"; DO NOT EDIT.

package tasks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TaskStatus_Nil-0]
	_ = x[TaskStatus_Running-1]
	_ = x[TaskStatus_NotRunning-2]
	_ = x[TaskStatus_Error-3]
	_ = x[TaskStatus_Stoped-4]
}

const _TaskStatus_name = "任务不存在任务运行中任务未运行任务出错任务已停止"

var _TaskStatus_index = [...]uint8{0, 15, 30, 45, 57, 72}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
