// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "lonzzi",
            "url": "https://ronki.moe",
            "email": "lonzzi@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bili/qrcode/getLoginInfo": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v2"
                ],
                "summary": "获取二维码状态",
                "parameters": [
                    {
                        "description": "oauthKey",
                        "name": "qrcode",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/bili/qrcode/getLoginUrl": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v2"
                ],
                "summary": "获取二维码登录链接",
                "responses": {}
            }
        },
        "/dynamic/latest": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v2"
                ],
                "summary": "获取up主最新动态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "up主id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/dynamic/listen": {
            "get": {
                "description": "根据设定的时间间隔监听up主动态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v2"
                ],
                "summary": "监听up主动态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "up主id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/dynamic/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v2"
                ],
                "summary": "获取传入的uid的状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "up主id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/dynamic/stop": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v2"
                ],
                "summary": "停止传入的uid的任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "up主id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:2333",
	BasePath:         "/v2",
	Schemes:          []string{},
	Title:            "bilibot",
	Description:      "a bilibot server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
