// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "lonzzi",
            "url": "https://ronki.moe",
            "email": "lonzzi@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bili/bot/check": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bili"
                ],
                "summary": "查询Bot登陆状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cookie当中的SESSDATA",
                        "name": "sessdata",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BotInfo"
                        }
                    }
                }
            }
        },
        "/bili/dynamic/getDynamic": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bili"
                ],
                "summary": "获取动态列表(访问b站api)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "up主id",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "动态偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/bilibot.Dynamic"
                            }
                        }
                    }
                }
            }
        },
        "/bili/qrcode/getLoginInfo": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bili"
                ],
                "summary": "获取二维码状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登陆链接中的 oauth_key",
                        "name": "oauth_key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/bili/qrcode/getLoginUrl": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bili"
                ],
                "summary": "获取二维码登录链接",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BiliQrCodeAuth"
                        }
                    }
                }
            }
        },
        "/bili/reply/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bili"
                ],
                "summary": "根据type与oid进行回复",
                "parameters": [
                    {
                        "description": "回复评论详细信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CommentInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyInfo"
                        }
                    }
                }
            }
        },
        "/web/author/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "需先添加up主之后才能监听动态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "添加up主",
                "parameters": [
                    {
                        "description": "up主id和BotID",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AuthorInfo"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/web/author/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "获取 up 主列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BotID",
                        "name": "bot_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Author"
                            }
                        }
                    }
                }
            }
        },
        "/web/bot/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据 Token 获取 Bot 列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "获取 Bot 列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Bot"
                            }
                        }
                    }
                }
            }
        },
        "/web/dynamic/latest": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "获取up主最新动态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BotID",
                        "name": "bot_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "up主ID",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/web/dynamic/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "获取 up 主的动态列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BotID",
                        "name": "bot_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "up主ID",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Dynamic"
                            }
                        }
                    }
                }
            }
        },
        "/web/dynamic/listen": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据设定的时间间隔监听up主动态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "监听up主动态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BotID",
                        "name": "bot_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "up主ID",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/web/dynamic/status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "获取传入的uid的状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BotID",
                        "name": "bot_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "up主ID",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/web/dynamic/stop": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "停止传入的uid的任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "BotID",
                        "name": "bot_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "up主ID",
                        "name": "mid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/web/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "站点用户登录",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "用户信息",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UserInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RegisteredToken"
                        }
                    }
                }
            }
        },
        "/web/refreshToken": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "刷新 AccessToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 刷新令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RegisteredToken"
                        }
                    }
                }
            }
        },
        "/web/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web"
                ],
                "summary": "站点用户注册",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "information",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UserInfo"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "api.AuthorInfo": {
            "type": "object",
            "properties": {
                "bot_id": {
                    "type": "string"
                },
                "mid": {
                    "type": "string"
                }
            }
        },
        "api.BiliQrCodeAuth": {
            "type": "object",
            "properties": {
                "oauth_key": {
                    "type": "string"
                },
                "ts": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "api.BotInfo": {
            "type": "object",
            "properties": {
                "bot_id": {
                    "type": "integer"
                },
                "face": {
                    "type": "string"
                },
                "is_login": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.CommentInfo": {
            "type": "object",
            "required": [
                "bot_id",
                "message",
                "oid",
                "type"
            ],
            "properties": {
                "bot_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "oid": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "api.RegisteredToken": {
            "type": "object",
            "properties": {
                "expire_at": {
                    "type": "integer"
                },
                "refresh_expire_at": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "api.ReplyInfo": {
            "type": "object",
            "properties": {
                "emote": {},
                "success_toast": {
                    "type": "string"
                }
            }
        },
        "api.UserInfo": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "bilibot.Author": {
            "type": "object",
            "properties": {
                "face": {
                    "description": "作者头像",
                    "type": "string"
                },
                "mid": {
                    "description": "作者ID",
                    "type": "integer"
                },
                "name": {
                    "description": "作者名称",
                    "type": "string"
                },
                "pub_ts": {
                    "description": "作者发布时间",
                    "type": "integer"
                }
            }
        },
        "bilibot.Content": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "object",
                    "properties": {
                        "text": {
                            "description": "动态内容",
                            "type": "string"
                        }
                    }
                }
            }
        },
        "bilibot.Dynamic": {
            "type": "object",
            "properties": {
                "id_str": {
                    "description": "动态ID",
                    "type": "string"
                },
                "modules": {
                    "type": "object",
                    "properties": {
                        "module_author": {
                            "description": "动态作者",
                            "$ref": "#/definitions/bilibot.Author"
                        },
                        "module_dynamic": {
                            "description": "动态内容",
                            "$ref": "#/definitions/bilibot.Content"
                        }
                    }
                }
            }
        },
        "model.Author": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "bot_id": {
                    "type": "string"
                },
                "face": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Bot": {
            "type": "object",
            "properties": {
                "bot_id": {
                    "type": "string"
                },
                "cookie": {
                    "type": "string"
                },
                "face": {
                    "type": "string"
                },
                "is_login": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.Dynamic": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "dynamic_id": {
                    "type": "string"
                },
                "ts": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/v2",
	Schemes:          []string{},
	Title:            "bilibot",
	Description:      "a bilibot server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
