name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            BiliUpDynamicBot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
